### ISSUE TITLE
Do you have Roadmap or Todolist?

### ISSUE THREAD

**Issue by ahmetcanaksu** [PineappleIOnic/sdk-for-rust#1]
If you provide a roadmap or todo list I can help you out too. After clarifying problems we can create a project timeline too.

**Comment by PineappleIOnic** [comment]
Hey There 👋 
This project is currently not really being worked on as I do not have the time to handle it anymore. If your interested in working on it you'll have to create an issue on Appwrite's sdk-generator repo https://github.com/appwrite/sdk-generator

**Comment by ahmetcanaksu** [comment]
I see, thanks for reply.
