### ISSUE TITLE
twig templates

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [PineappleIOnic/sdk-for-rust#2]
Hi,

Do you have the twig templates still roaming somewhere to share?

Cheers

**Comment by PineappleIOnic** [comment]
You can find them here: https://github.com/PineappleIOnic/sdk-generator/tree/rust-response-models, I will warn you though they are incredibly outdated and behind the main branch

**Comment by HerrMuellerluedenscheid** [comment]
Thanks for the headsup. I switched to openapi instead which works fine.
